import os
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise RuntimeError("A variável de ambiente GROQ_API_KEY não está definida.")

CORS_ORIGINS = ["*"]
CORS_CREDENTIALS = True
CORS_METHODS = ["*"]
CORS_HEADERS = ["*"]

EASYOCR_LANGUAGES = ['pt', 'en']
EASYOCR_GPU = False
TESSERACT_DEFAULT_LANG = 'por'
TESSERACT_FALLBACK_LANG = 'eng'

OCR_DPI = 300
OCR_PARAREL_PREPROCESSING = True

OCR_PARAREL_PREPROCESSING_LANG = True
OCR_MAX_WORKERS = 4

CHUNK_SIZE = 4000
CHUNK_OVERLAP = 500
MAX_TOKENS_PER_CHUNK = 4000
TOKEN_ESTIMATION_RATIO = 4  # 1 token ≈ 4 characters

UNSTRUCTURED_TIMEOUT = 15
UNSTRUCTURED_MODE = "single"
UNSTRUCTURED_STRATEGY = "fast"

LLM_MODEL = "llama-3.3-70b-versatile"
LLM_MAX_TOKENS = 1000

TABLE_MIN_COLUMNS = 2
TABLE_Y_POSITION_TOLERANCE = 5
TABLE_X_POSITION_BUCKET = 50
TABLE_COLUMN_VARIATION_TOLERANCE = 2
